import { Injectable, inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

export type AppLanguage = 'eng' | 'rus' | 'kaz';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private platformId = inject(PLATFORM_ID);

  currentLang: AppLanguage = 'eng';

  private translations: Record<AppLanguage, Record<string, string>> = {
    eng: {
      listings: 'Listings',
      createListing: 'Create Listing',
      login: 'Login',
      register: 'Register',
      profile: 'Profile',
      myListings: 'My Listings',
      favorites: 'Favorites',
      settings: 'Settings',
      logout: 'Logout',

      exploreListings: 'Explore Listings',
      searchFilterSort: 'Search, filter, and sort items easily',
      search: 'Search',
      category: 'Category',
      sortBy: 'Sort by',
      searchByTitle: 'Search by title',
      allCategories: 'All Categories',
      newest: 'Newest',
      applyFilters: 'Apply Filters',
      clear: 'Clear',

      noListingsFound: 'No listings found',
      tryChangingFilters: 'Try changing your filters or be the first to publish an item.',
      createListingBtn: 'Create Listing',

      homeBadge: 'Student marketplace platform',
      homeTitle: 'Buy, sell, and discover items on UniTrade',
      homeSubtitle: 'A clean campus marketplace where students can post listings, find useful products, save favorites, and manage everything in one place.',
      browseListings: 'Browse Listings',

      fast: 'Fast',
      fastDesc: 'Simple posting flow',
      smart: 'Smart',
      smartDesc: 'Filter and category search',
      safe: 'Safe',
      safeDesc: 'Campus-focused trading',

      browseByCategory: 'Browse by Category',
      browseByCategoryDesc: 'Find exactly what you need quickly and easily.',

      electronics: 'Electronics',
      booksStudy: 'Books & Study Materials',
      homeDorm: 'Home & Dorm Items',

      electronicsDesc: 'Laptops, chargers, keyboards and other useful tech for campus life.',
      booksDesc: 'Textbooks, notes, printed materials and study sets for students.',
      homeDormDesc: 'Lamps, storage boxes, pillows, kitchen items and dorm essentials.',

      whyWorks: 'Why UniTrade works well',
      whyWorksDesc: 'Designed for a simple and modern student marketplace experience.',

      easyPosting: 'Easy posting',
      easyPostingDesc: 'Create listings with clear details, categories, price, and photo upload.',
      personalDashboard: 'Personal dashboard',
      personalDashboardDesc: 'Manage your own listings, edit them, or delete them whenever needed.',
      favoritesSystem: 'Favorites system',
      favoritesSystemDesc: 'Save interesting listings and return to them later without searching again.',

      listingsBadge: 'Student marketplace',
      listingsTitle: 'Find what you need on UniTrade',
      listingsSubtitle: 'Browse listings, discover useful items, and connect with students inside your campus community.',
      priceLowHigh: 'Price: Low to High',
      priceHighLow: 'Price: High to Low',
      loadingListings: 'Loading listings...',
      viewDetails: 'View Details',
      campusLocationNotSpecified: 'Campus location not specified',
      failedToLoadCategories: 'Failed to load categories',
      failedToLoadListings: 'Failed to load listings',
      failedToRemoveFavorite: 'Failed to remove from favorites. Please log in.',
      needLoginToFavorite: 'You need to log in to add to favorites',

      savedMarketplaceItems: 'Saved marketplace items',
      favoritesSubtitle: 'Keep track of listings you liked and come back to them anytime.',
      loadingFavorites: 'Loading favorites...',
      noFavoritesYet: 'No favorites yet',
      saveListingsLater: 'Save listings you like so you can find them later.',
      view: 'View',
      remove: 'Remove',
      failedToLoadFavorites: 'Failed to load favorites',

      loadingListing: 'Loading listing...',
      failedToLoadListing: 'Failed to load listing',
      notSpecified: 'Not specified',
      views: 'Views',
      sellerContacts: 'Seller Contacts',
      rating: 'Rating',
      average: 'Average',
      ratings: 'ratings',
      addToFavorites: 'Add to Favorites',
      backToListings: 'Back to Listings',
      comments: 'Comments',
      writeComment: 'Write a comment...',
      postComment: 'Post Comment',
      noCommentsYet: 'No comments yet.',
      failedToAddComment: 'Failed to add comment',
      needLoginFirst: 'You need to log in first',
      sellerContactsNotAvailable: 'Seller contacts are not available.',

      studentMarketplace: 'Student marketplace',
      loginIntro: 'Sign in to browse listings, save favorites, and manage your campus marketplace account.',
      welcomeBack: 'Welcome back to UniTrade',
      username: 'Username',
      password: 'Password',
      signingIn: 'Signing in...',
      or: 'or',
      dontHaveAccount: 'Don’t have an account?',
      usernameRequired: 'Username is required',
      passwordRequired: 'Password is required',
      passwordMinLength: 'Password must be at least 8 characters',
      invalidUsernameOrPassword: 'Invalid username or password',

      yourMarketplacePosts: 'Your marketplace posts',
      manageYourListingsSubtitle: 'Manage, edit, and remove the items you published on UniTrade.',
      loadingYourListings: 'Loading your listings...',
      youHaveNoListingsYet: 'You have no listings yet',
      createFirstItemPrompt: 'Create your first item and start sharing it with other students.',
      edit: 'Edit',
      delete: 'Delete',
      failedToLoadYourListings: 'Failed to load your listings',
      confirmDeleteListing: 'Are you sure you want to delete this listing?',
      failedToDeleteListing: 'Failed to delete listing',

      profileSettings: 'Profile Settings',
      profileSettingsSubtitle: 'Manage your account details and contact information.',
      loadingProfile: 'Loading profile...',
      failedToLoadProfile: 'Failed to load profile',
      profileUpdatedSuccessfully: 'Profile updated successfully',
      failedToUpdateProfile: 'Failed to update profile',
      phoneNumberWhatsApp: 'Phone Number (for WhatsApp)',
      phoneExample: 'e.g. +77001234567',
      telegramUsername: 'Telegram Username',
      telegramWithoutAt: 'without @',
      bioAboutMe: 'Bio / About Me',
      bioPlaceholder: 'Tell buyers a bit about yourself...',
      universityId: 'University ID',
      studentId: 'Student ID',
      dormitoryExample: 'e.g. Block A',
      roomExample: 'e.g. 402',
      saving: 'Saving...',
      saveChanges: 'Save Changes',

      registerIntro: 'Create your account and start buying or selling inside the student community.',
      createAccount: 'Create account',
      joinInFewSteps: 'Join UniTrade in a few steps',
      creating: 'Creating...',
      alreadyHaveAccount: 'Already have an account?',
      usernameMinLength: 'Username must be at least 3 characters',
      emailRequired: 'Email is required',
      validEmailRequired: 'Enter a valid email address',
      registrationFailed: 'Registration failed. Please check your data.',

      newMarketplacePost: 'New marketplace post',
      createListingIntro: 'Add your item to UniTrade and let other students discover it quickly.',
      listingDetails: 'Listing details',
      fillItemInfo: 'Fill in the item information below',
      title: 'Title',
      description: 'Description',
      price: 'Price',
      location: 'Location',
      locationDormCampus: 'Location (Dormitory / Campus)',
      uploadPhoto: 'Upload photo',
      changePhoto: 'Change photo',
      condition: 'Condition',
      status: 'Status',
      newCondition: 'New',
      usedCondition: 'Used',
      available: 'Available',
      reserved: 'Reserved',
      sold: 'Sold',
      selectCategory: 'Select category',
      contactInformation: 'Contact Information',
      phone: 'Phone',
      telegram: 'Telegram',
      whatsapp: 'WhatsApp',
      email: 'Email',
      dormitory: 'Dormitory',
      room: 'Room',
      phoneNumber: 'Phone number',
      telegramPlaceholder: '@username',
      whatsappNumber: 'WhatsApp number',
      publishing: 'Publishing...',
      publishListing: 'Publish listing',
      wantToGoBack: 'Want to go back?',
      failedToSaveContactInformation: 'Failed to save contact information',
      failedToCreateListing: 'Failed to create listing',
      titleRequired: 'Title is required',
      titleMinLength: 'Title must be at least 3 characters',
      descriptionRequired: 'Description is required',
      descriptionMinLength: 'Description must be at least 10 characters',
      priceRequired: 'Price is required',
      priceGreaterThanZero: 'Price must be greater than 0',
      categoryRequired: 'Category is required',

      manageMarketplacePost: 'Manage your marketplace post',
      editListing: 'Edit Listing',
      editListingIntro: 'Update your item information and keep your UniTrade post fresh and accurate.',
      editDetails: 'Edit details',
      updateItemInfo: 'Update the item information below',
      noPhotoUploadedYet: 'No photo uploaded yet.',
      wantToReturn: 'Want to return?',
      backToMyListings: 'Back to My Listings',
      failedToUpdateListing: 'Failed to update listing'
    },

    rus: {
      listings: 'Объявления',
      createListing: 'Создать объявление',
      login: 'Войти',
      register: 'Регистрация',
      profile: 'Профиль',
      myListings: 'Мои объявления',
      favorites: 'Избранное',
      settings: 'Настройки',
      logout: 'Выйти',

      exploreListings: 'Объявления',
      searchFilterSort: 'Ищите, фильтруйте и сортируйте товары',
      search: 'Поиск',
      category: 'Категория',
      sortBy: 'Сортировать по',
      searchByTitle: 'Поиск по названию',
      allCategories: 'Все категории',
      newest: 'Сначала новые',
      applyFilters: 'Применить фильтры',
      clear: 'Очистить',

      noListingsFound: 'Объявления не найдены',
      tryChangingFilters: 'Попробуйте изменить фильтры или создайте объявление первым.',
      createListingBtn: 'Создать объявление',

      homeBadge: 'Студенческая торговая платформа',
      homeTitle: 'Покупай, продавай и находи нужные вещи на UniTrade',
      homeSubtitle: 'Удобная студенческая площадка, где можно размещать объявления, находить полезные товары, сохранять избранное и управлять всем в одном месте.',
      browseListings: 'Смотреть объявления',

      fast: 'Быстро',
      fastDesc: 'Простое размещение объявлений',
      smart: 'Умно',
      smartDesc: 'Поиск по фильтрам и категориям',
      safe: 'Безопасно',
      safeDesc: 'Платформа для студентов кампуса',

      browseByCategory: 'Поиск по категориям',
      browseByCategoryDesc: 'Быстро находите именно то, что вам нужно.',

      electronics: 'Электроника',
      booksStudy: 'Книги и учебные материалы',
      homeDorm: 'Товары для дома и общежития',

      electronicsDesc: 'Ноутбуки, зарядки, клавиатуры и другая полезная техника для учёбы.',
      booksDesc: 'Учебники, конспекты, распечатки и материалы для студентов.',
      homeDormDesc: 'Лампы, коробки для хранения, подушки, кухонные вещи и всё для общежития.',

      whyWorks: 'Почему UniTrade удобен',
      whyWorksDesc: 'Создан для простого и современного студенческого маркетплейса.',

      easyPosting: 'Удобное размещение',
      easyPostingDesc: 'Создавайте объявления с понятным описанием, категорией, ценой и фото.',
      personalDashboard: 'Личный кабинет',
      personalDashboardDesc: 'Управляйте своими объявлениями, редактируйте или удаляйте их в любое время.',
      favoritesSystem: 'Система избранного',
      favoritesSystemDesc: 'Сохраняйте интересные объявления и возвращайтесь к ним позже без повторного поиска.',

      listingsBadge: 'Студенческий маркетплейс',
      listingsTitle: 'Найди то, что тебе нужно, на UniTrade',
      listingsSubtitle: 'Просматривайте объявления, находите полезные вещи и связывайтесь со студентами внутри кампуса.',
      priceLowHigh: 'Цена: по возрастанию',
      priceHighLow: 'Цена: по убыванию',
      loadingListings: 'Загрузка объявлений...',
      viewDetails: 'Подробнее',
      campusLocationNotSpecified: 'Местоположение в кампусе не указано',
      failedToLoadCategories: 'Не удалось загрузить категории',
      failedToLoadListings: 'Не удалось загрузить объявления',
      failedToRemoveFavorite: 'Не удалось удалить из избранного. Пожалуйста, войдите в систему.',
      needLoginToFavorite: 'Нужно войти в систему, чтобы добавить в избранное',

      savedMarketplaceItems: 'Сохранённые товары',
      favoritesSubtitle: 'Следите за понравившимися объявлениями и возвращайтесь к ним в любое время.',
      loadingFavorites: 'Загрузка избранного...',
      noFavoritesYet: 'Избранного пока нет',
      saveListingsLater: 'Сохраняйте понравившиеся объявления, чтобы быстро вернуться к ним позже.',
      view: 'Открыть',
      remove: 'Удалить',
      failedToLoadFavorites: 'Не удалось загрузить избранное',

      loadingListing: 'Загрузка объявления...',
      failedToLoadListing: 'Не удалось загрузить объявление',
      notSpecified: 'Не указано',
      views: 'Просмотры',
      sellerContacts: 'Контакты продавца',
      rating: 'Рейтинг',
      average: 'Средний',
      ratings: 'оценок',
      addToFavorites: 'Добавить в избранное',
      backToListings: 'Назад к объявлениям',
      comments: 'Комментарии',
      writeComment: 'Напишите комментарий...',
      postComment: 'Отправить комментарий',
      noCommentsYet: 'Комментариев пока нет.',
      failedToAddComment: 'Не удалось добавить комментарий',
      needLoginFirst: 'Сначала войдите в систему',
      sellerContactsNotAvailable: 'Контакты продавца недоступны.',

      studentMarketplace: 'Студенческий маркетплейс',
      loginIntro: 'Войдите, чтобы просматривать объявления, сохранять избранное и управлять своим аккаунтом.',
      welcomeBack: 'С возвращением в UniTrade',
      username: 'Имя пользователя',
      password: 'Пароль',
      signingIn: 'Вход...',
      or: 'или',
      dontHaveAccount: 'Нет аккаунта?',
      usernameRequired: 'Имя пользователя обязательно',
      passwordRequired: 'Пароль обязателен',
      passwordMinLength: 'Пароль должен быть не менее 8 символов',
      invalidUsernameOrPassword: 'Неверное имя пользователя или пароль',

      yourMarketplacePosts: 'Ваши объявления',
      manageYourListingsSubtitle: 'Управляйте, редактируйте и удаляйте свои объявления в UniTrade.',
      loadingYourListings: 'Загрузка ваших объявлений...',
      youHaveNoListingsYet: 'У вас пока нет объявлений',
      createFirstItemPrompt: 'Создайте своё первое объявление и поделитесь им с другими студентами.',
      edit: 'Редактировать',
      delete: 'Удалить',
      failedToLoadYourListings: 'Не удалось загрузить ваши объявления',
      confirmDeleteListing: 'Вы уверены, что хотите удалить это объявление?',
      failedToDeleteListing: 'Не удалось удалить объявление',

      profileSettings: 'Настройки профиля',
      profileSettingsSubtitle: 'Управляйте данными аккаунта и контактной информацией.',
      loadingProfile: 'Загрузка профиля...',
      failedToLoadProfile: 'Не удалось загрузить профиль',
      profileUpdatedSuccessfully: 'Профиль успешно обновлён',
      failedToUpdateProfile: 'Не удалось обновить профиль',
      phoneNumberWhatsApp: 'Номер телефона (для WhatsApp)',
      phoneExample: 'например, +77001234567',
      telegramUsername: 'Имя пользователя Telegram',
      telegramWithoutAt: 'без @',
      bioAboutMe: 'О себе',
      bioPlaceholder: 'Немного расскажите покупателям о себе...',
      universityId: 'ID университета',
      studentId: 'Студенческий ID',
      dormitoryExample: 'например, Блок A',
      roomExample: 'например, 402',
      saving: 'Сохранение...',
      saveChanges: 'Сохранить изменения',

      registerIntro: 'Создайте аккаунт и начните покупать или продавать внутри студенческого сообщества.',
      createAccount: 'Создать аккаунт',
      joinInFewSteps: 'Присоединяйтесь к UniTrade за пару шагов',
      creating: 'Создание...',
      alreadyHaveAccount: 'Уже есть аккаунт?',
      usernameMinLength: 'Имя пользователя должно быть не менее 3 символов',
      emailRequired: 'Email обязателен',
      validEmailRequired: 'Введите корректный email',
      registrationFailed: 'Регистрация не удалась. Проверьте введённые данные.',

      newMarketplacePost: 'Новое объявление',
      createListingIntro: 'Добавьте свой товар в UniTrade, чтобы другие студенты могли быстро его найти.',
      listingDetails: 'Детали объявления',
      fillItemInfo: 'Заполните информацию о товаре ниже',
      title: 'Название',
      description: 'Описание',
      price: 'Цена',
      location: 'Местоположение',
      locationDormCampus: 'Местоположение (общежитие / кампус)',
      uploadPhoto: 'Загрузить фото',
      changePhoto: 'Изменить фото',
      condition: 'Состояние',
      status: 'Статус',
      newCondition: 'Новый',
      usedCondition: 'Б/у',
      available: 'Доступно',
      reserved: 'Забронировано',
      sold: 'Продано',
      selectCategory: 'Выберите категорию',
      contactInformation: 'Контактная информация',
      phone: 'Телефон',
      telegram: 'Telegram',
      whatsapp: 'WhatsApp',
      email: 'Email',
      dormitory: 'Общежитие',
      room: 'Комната',
      phoneNumber: 'Номер телефона',
      telegramPlaceholder: '@username',
      whatsappNumber: 'Номер WhatsApp',
      publishing: 'Публикация...',
      publishListing: 'Опубликовать объявление',
      wantToGoBack: 'Хотите вернуться?',
      failedToSaveContactInformation: 'Не удалось сохранить контактную информацию',
      failedToCreateListing: 'Не удалось создать объявление',
      titleRequired: 'Название обязательно',
      titleMinLength: 'Название должно быть не менее 3 символов',
      descriptionRequired: 'Описание обязательно',
      descriptionMinLength: 'Описание должно быть не менее 10 символов',
      priceRequired: 'Цена обязательна',
      priceGreaterThanZero: 'Цена должна быть больше 0',
      categoryRequired: 'Категория обязательна',

      manageMarketplacePost: 'Управляйте своим объявлением',
      editListing: 'Редактировать объявление',
      editListingIntro: 'Обновляйте информацию о товаре и поддерживайте объявление актуальным.',
      editDetails: 'Редактирование',
      updateItemInfo: 'Обновите информацию о товаре ниже',
      noPhotoUploadedYet: 'Фото пока не загружено.',
      wantToReturn: 'Хотите вернуться?',
      backToMyListings: 'Назад к моим объявлениям',
      failedToUpdateListing: 'Не удалось обновить объявление'
    },

    kaz: {
      listings: 'Хабарландырулар',
      createListing: 'Хабарландыру қосу',
      login: 'Кіру',
      register: 'Тіркелу',
      profile: 'Профиль',
      myListings: 'Менің хабарландыруларым',
      favorites: 'Таңдаулылар',
      settings: 'Баптаулар',
      logout: 'Шығу',

      exploreListings: 'Хабарландыруларды қарау',
      searchFilterSort: 'Тауарларды іздеңіз, сүзгіден өткізіңіз және сұрыптаңыз',
      search: 'Іздеу',
      category: 'Санат',
      sortBy: 'Сұрыптау',
      searchByTitle: 'Атауы бойынша іздеу',
      allCategories: 'Барлық санаттар',
      newest: 'Жаңалары',
      applyFilters: 'Сүзгілерді қолдану',
      clear: 'Тазалау',

      noListingsFound: 'Хабарландыру табылмады',
      tryChangingFilters: 'Сүзгілерді өзгертіңіз немесе бірінші болып хабарландыру қосыңыз.',
      createListingBtn: 'Хабарландыру қосу',

      homeBadge: 'Студенттерге арналған сауда платформасы',
      homeTitle: 'UniTrade арқылы сатып ал, сат және керегіңді тап',
      homeSubtitle: 'Студенттерге арналған ыңғайлы алаң: хабарландыру жариялау, пайдалы заттарды табу, таңдаулыларға сақтау және бәрін бір жерден басқару.',
      browseListings: 'Хабарландыруларды қарау',

      fast: 'Жылдам',
      fastDesc: 'Хабарландыру қосудың оңай жолы',
      smart: 'Ақылды',
      smartDesc: 'Сүзгі және санат бойынша іздеу',
      safe: 'Қауіпсіз',
      safeDesc: 'Кампус студенттеріне арналған платформа',

      browseByCategory: 'Санат бойынша қарау',
      browseByCategoryDesc: 'Өзіңізге керек затты тез әрі оңай табыңыз.',

      electronics: 'Электроника',
      booksStudy: 'Кітаптар және оқу материалдары',
      homeDorm: 'Үй және жатақхана заттары',

      electronicsDesc: 'Ноутбуктер, қуаттағыштар, пернетақталар және оқу үшін пайдалы техника.',
      booksDesc: 'Оқулықтар, конспектілер, баспа материалдары және студенттерге арналған жинақтар.',
      homeDormDesc: 'Шамдар, сақтау қораптары, жастықтар, асүй заттары және жатақханаға керек бұйымдар.',

      whyWorks: 'UniTrade неге ыңғайлы',
      whyWorksDesc: 'Қарапайым әрі заманауи студенттік маркетплейс үшін жасалған.',

      easyPosting: 'Оңай жариялау',
      easyPostingDesc: 'Түсінікті сипаттама, санат, баға және фото арқылы хабарландыру жасаңыз.',
      personalDashboard: 'Жеке кабинет',
      personalDashboardDesc: 'Өз хабарландыруларыңызды басқарыңыз, қажет болса өңдеңіз немесе өшіріңіз.',
      favoritesSystem: 'Таңдаулылар жүйесі',
      favoritesSystemDesc: 'Ұнаған хабарландыруларды сақтап, кейін оңай қайта оралыңыз.',

      listingsBadge: 'Студенттік маркетплейс',
      listingsTitle: 'UniTrade арқылы керек затыңды тап',
      listingsSubtitle: 'Хабарландыруларды қарап, пайдалы заттарды тауып, кампустағы студенттермен байланыс орнатыңыз.',
      priceLowHigh: 'Бағасы: өсу ретімен',
      priceHighLow: 'Бағасы: кему ретімен',
      loadingListings: 'Хабарландырулар жүктелуде...',
      viewDetails: 'Толығырақ',
      campusLocationNotSpecified: 'Кампустағы орын көрсетілмеген',
      failedToLoadCategories: 'Санаттарды жүктеу мүмкін болмады',
      failedToLoadListings: 'Хабарландыруларды жүктеу мүмкін болмады',
      failedToRemoveFavorite: 'Таңдаулылардан өшіру мүмкін болмады. Жүйеге кіріңіз.',
      needLoginToFavorite: 'Таңдаулыларға қосу үшін жүйеге кіру керек',

      savedMarketplaceItems: 'Сақталған тауарлар',
      favoritesSubtitle: 'Ұнаған хабарландыруларды бақылап, оларға кез келген уақытта қайта оралыңыз.',
      loadingFavorites: 'Таңдаулылар жүктелуде...',
      noFavoritesYet: 'Таңдаулылар әлі жоқ',
      saveListingsLater: 'Ұнаған хабарландыруларды сақтап, кейін оңай табыңыз.',
      view: 'Ашу',
      remove: 'Өшіру',
      failedToLoadFavorites: 'Таңдаулыларды жүктеу мүмкін болмады',

      loadingListing: 'Хабарландыру жүктелуде...',
      failedToLoadListing: 'Хабарландыруды жүктеу мүмкін болмады',
      notSpecified: 'Көрсетілмеген',
      views: 'Қаралымдар',
      sellerContacts: 'Сатушы байланыстары',
      rating: 'Рейтинг',
      average: 'Орташа',
      ratings: 'баға',
      addToFavorites: 'Таңдаулыларға қосу',
      backToListings: 'Хабарландыруларға оралу',
      comments: 'Пікірлер',
      writeComment: 'Пікір жазыңыз...',
      postComment: 'Пікір жіберу',
      noCommentsYet: 'Әзірге пікір жоқ.',
      failedToAddComment: 'Пікір қосу мүмкін болмады',
      needLoginFirst: 'Алдымен жүйеге кіріңіз',
      sellerContactsNotAvailable: 'Сатушы байланыстары қолжетімсіз.',

      studentMarketplace: 'Студенттік маркетплейс',
      loginIntro: 'Хабарландыруларды көру, таңдаулыларды сақтау және аккаунтыңызды басқару үшін кіріңіз.',
      welcomeBack: 'UniTrade-қа қайта қош келдіңіз',
      username: 'Пайдаланушы аты',
      password: 'Құпиясөз',
      signingIn: 'Кіру...',
      or: 'немесе',
      dontHaveAccount: 'Аккаунтыңыз жоқ па?',
      usernameRequired: 'Пайдаланушы аты міндетті',
      passwordRequired: 'Құпиясөз міндетті',
      passwordMinLength: 'Құпиясөз кемінде 8 таңба болуы керек',
      invalidUsernameOrPassword: 'Пайдаланушы аты немесе құпиясөз қате',

      yourMarketplacePosts: 'Сіздің хабарландыруларыңыз',
      manageYourListingsSubtitle: 'UniTrade-тағы хабарландыруларыңызды басқарыңыз, өңдеңіз және өшіріңіз.',
      loadingYourListings: 'Хабарландыруларыңыз жүктелуде...',
      youHaveNoListingsYet: 'Сізде әлі хабарландыру жоқ',
      createFirstItemPrompt: 'Алғашқы хабарландыруыңызды жасап, оны басқа студенттермен бөлісіңіз.',
      edit: 'Өңдеу',
      delete: 'Өшіру',
      failedToLoadYourListings: 'Хабарландыруларыңызды жүктеу мүмкін болмады',
      confirmDeleteListing: 'Бұл хабарландыруды өшіргіңіз келетініне сенімдісіз бе?',
      failedToDeleteListing: 'Хабарландыруды өшіру мүмкін болмады',

      profileSettings: 'Профиль баптаулары',
      profileSettingsSubtitle: 'Аккаунт деректері мен байланыс ақпаратын басқарыңыз.',
      loadingProfile: 'Профиль жүктелуде...',
      failedToLoadProfile: 'Профильді жүктеу мүмкін болмады',
      profileUpdatedSuccessfully: 'Профиль сәтті жаңартылды',
      failedToUpdateProfile: 'Профильді жаңарту мүмкін болмады',
      phoneNumberWhatsApp: 'Телефон нөмірі (WhatsApp үшін)',
      phoneExample: 'мысалы, +77001234567',
      telegramUsername: 'Telegram пайдаланушы аты',
      telegramWithoutAt: '@ белгісінсіз',
      bioAboutMe: 'Өзіңіз туралы',
      bioPlaceholder: 'Сатып алушыларға өзіңіз туралы қысқаша жазыңыз...',
      universityId: 'Университет ID',
      studentId: 'Студенттік ID',
      dormitoryExample: 'мысалы, A блок',
      roomExample: 'мысалы, 402',
      saving: 'Сақталуда...',
      saveChanges: 'Өзгерістерді сақтау',

      registerIntro: 'Аккаунт жасап, студенттік қауымдастық ішінде сатып алуды не сатуды бастаңыз.',
      createAccount: 'Аккаунт жасау',
      joinInFewSteps: 'UniTrade-қа бірнеше қадаммен қосылыңыз',
      creating: 'Жасалуда...',
      alreadyHaveAccount: 'Аккаунтыңыз бар ма?',
      usernameMinLength: 'Пайдаланушы аты кемінде 3 таңба болуы керек',
      emailRequired: 'Email міндетті',
      validEmailRequired: 'Жарамды email енгізіңіз',
      registrationFailed: 'Тіркелу сәтсіз аяқталды. Деректерді тексеріңіз.',

      newMarketplacePost: 'Жаңа хабарландыру',
      createListingIntro: 'Тауарыңызды UniTrade-қа қосып, басқа студенттерге тез табуға мүмкіндік беріңіз.',
      listingDetails: 'Хабарландыру мәліметтері',
      fillItemInfo: 'Төменде тауар туралы ақпаратты толтырыңыз',
      title: 'Атауы',
      description: 'Сипаттама',
      price: 'Бағасы',
      location: 'Орналасуы',
      locationDormCampus: 'Орналасуы (жатақхана / кампус)',
      uploadPhoto: 'Фото жүктеу',
      changePhoto: 'Фотоны өзгерту',
      condition: 'Жағдайы',
      status: 'Мәртебесі',
      newCondition: 'Жаңа',
      usedCondition: 'Қолданылған',
      available: 'Қолжетімді',
      reserved: 'Брондалған',
      sold: 'Сатылған',
      selectCategory: 'Санатты таңдаңыз',
      contactInformation: 'Байланыс ақпараты',
      phone: 'Телефон',
      telegram: 'Telegram',
      whatsapp: 'WhatsApp',
      email: 'Email',
      dormitory: 'Жатақхана',
      room: 'Бөлме',
      phoneNumber: 'Телефон нөмірі',
      telegramPlaceholder: '@username',
      whatsappNumber: 'WhatsApp нөмірі',
      publishing: 'Жариялануда...',
      publishListing: 'Хабарландыру жариялау',
      wantToGoBack: 'Қайтып барғыңыз келе ме?',
      failedToSaveContactInformation: 'Байланыс ақпаратын сақтау мүмкін болмады',
      failedToCreateListing: 'Хабарландыру жасау мүмкін болмады',
      titleRequired: 'Атау міндетті',
      titleMinLength: 'Атау кемінде 3 таңба болуы керек',
      descriptionRequired: 'Сипаттама міндетті',
      descriptionMinLength: 'Сипаттама кемінде 10 таңба болуы керек',
      priceRequired: 'Бағасы міндетті',
      priceGreaterThanZero: 'Бағасы 0-ден үлкен болуы керек',
      categoryRequired: 'Санат міндетті',

      manageMarketplacePost: 'Хабарландыруыңызды басқарыңыз',
      editListing: 'Хабарландыруды өңдеу',
      editListingIntro: 'Тауар ақпаратын жаңартып, хабарландыруыңызды өзекті күйде ұстаңыз.',
      editDetails: 'Мәліметтерді өңдеу',
      updateItemInfo: 'Төменде тауар туралы ақпаратты жаңартыңыз',
      noPhotoUploadedYet: 'Әзірге фото жүктелмеген.',
      wantToReturn: 'Қайтып оралғыңыз келе ме?',
      backToMyListings: 'Менің хабарландыруларыма оралу',
      failedToUpdateListing: 'Хабарландыруды жаңарту мүмкін болмады'
    }
  };

  constructor() {
    if (isPlatformBrowser(this.platformId)) {
      const saved = localStorage.getItem('app_lang') as AppLanguage | null;
      if (saved) {
        this.currentLang = saved;
      }
    }
  }

  setLanguage(lang: AppLanguage): void {
    this.currentLang = lang;

    if (isPlatformBrowser(this.platformId)) {
      localStorage.setItem('app_lang', lang);
    }
  }

  t(key: string): string {
    return this.translations[this.currentLang]?.[key] || key;
  }
}